export const grammarCourses = {
  A1: [
    "Bestimmte und Unbestimmte Artikel",
    "Personalpronomen",
    "Präsens",
    "Negation",
    "Grundlegende Wortstellung",
    "Modalverben",
    "Einfache Präpositionen",
    "Possessivpronomen",
    "Fragewörter",
    "Trennbare Verben",
    "Imperativ",
    "Reflexive Verben",
  ],
  A2: [
    "Akkusativ",
    "Dativ",
    "Perfekt",
    "Präteritum",
    "Komparativ",
    "Superlativ",
    "Untrennbare Verben",
    "Nebensätze",
    "Adjektivdeklination",
    "Relativsätze",
    "Genitiv",
    "Indirekte Fragen",
    "Adverbien",
  ],
  B1: [
    "Plusquamperfekt",
    "Passiv",
    "Relativsätze mit Präpositionen",
    "Konjunktiv II",
    "Indirekte Rede",
    "Erweiterte Wortstellung",
    "Präpositionen mit Genitiv",
    "Modalverben im Präteritum",
    "Partizipien als Adjektive",
    "Komplexe Satzstrukturen",
  ],
  B2: [
    "Konjunktiv I",
    "Erweiterter Konjunktiv II",
    "Erweitertes Passiv",
    "Infinitivsätze mit 'zu'",
    "Partizipialsätze",
    "Nominalisierung",
    "Präpositionen mit speziellen Bedeutungen",
    "Erweiterte Adjektivendungen in komplexen Sätzen",
    "Verben mit festen Präpositionen",
    "Idiomatiche Ausdrücke",
    "Stilistische Mittel",
    "Formelle und informelle Sprache",
  ],
};
