export const suggestionTopics = {
  A1: [
    "Family",
    "Numbers",
    "Colors",
    "Food & Drinks",
    "Animals",
    "Daily Routine",
    "Clothing",
    "Home & Living",
    "Professions",
    "Transportation",
  ],
  A2: [
    "Weather",
    "Travel",
    "Shopping",
    "Health",
    "Hobbies",
    "Directions",
    "Time & Dates",
    "School",
    "Restaurant",
    "Emotions",
  ],
  B1: [
    "Work Environment",
    "Politics",
    "Technology",
    "Education",
    "Environment",
    "Media",
    "Culture",
    "Relationships",
    "Finance",
    "Travel Planning",
  ],
  B2: [
    "Abstract Concepts",
    "Literature",
    "Philosophy",
    "Career Development",
    "Science",
    "Law",
    "Psychology",
    "Global Issues",
    "Advanced Politics",
    "Economics",
  ],
};
