export const suggestionTopics = {
  A1: [
    "Familie",
    "Zahlen",
    "Farben",
    "Essen & Getränke",
    "Tiere",
    "Tägliche Routine",
    "Kleidung",
    "Zuhause & Wohnen",
    "Berufe",
    "Transportmittel",
  ],
  A2: [
    "Wetter",
    "Reisen",
    "Einkaufen",
    "Gesundheit",
    "Hobbys",
    "Wegbeschreibungen",
    "Uhrzeit & Datum",
    "Schule",
    "Restaurant",
    "Gefühle",
  ],
  B1: [
    "Arbeitsumgebung",
    "Politik",
    "Technologie",
    "Bildung",
    "Umwelt",
    "Medien",
    "Kultur",
    "Beziehungen",
    "Finanzen",
    "Reiseplanung",
  ],
  B2: [
    "Abstrakte Konzepte",
    "Literatur",
    "Philosophie",
    "Karriereentwicklung",
    "Wissenschaft",
    "Recht",
    "Psychologie",
    "Globale Themen",
    "Fortgeschrittene Politik",
    "Wirtschaft",
  ],
};
